// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dzxmfbykkcffwmazuwpg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR6eG1mYnlra2NmZndtYXp1d3BnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NTYzMzAsImV4cCI6MjA2NzEzMjMzMH0.6dvNoG8g4MC_LxJl5miffySCPLRXRw9FcgD-zxHVs6c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});